# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(default='IN', max_length=8),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='suite',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='tags',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
