# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20170130_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='suite',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
