# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20170130_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='oam_url_part',
            field=models.CharField(default='uniq_url', max_length=255, unique=True),
        ),
    ]
