# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customer_oam_url_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
    ]
