# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('billing', '0007_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name='address',
            index_together=set([('customer', 'active', 'label')]),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('content_type', 'object_id', 'created_at')]),
        ),
        migrations.AlterIndexTogether(
            name='customer',
            index_together=set([('active', 'oam_url_part')]),
        ),
        migrations.AlterIndexTogether(
            name='invoice',
            index_together=set([('customer', 'due_date')]),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Invoice'),
        ),
        migrations.AddField(
            model_name='credit',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.InvoiceItem'),
        ),
        migrations.AlterIndexTogether(
            name='invoiceitem',
            index_together=set([('invoice',)]),
        ),
        migrations.AlterIndexTogether(
            name='credit',
            index_together=set([('invoice_item',)]),
        ),
    ]
