# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20170202_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credit',
            new_name='InvoiceItemCredit',
        ),
    ]
