# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20170203_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_mime_type',
            field=models.CharField(default='image/jpeg', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
