# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20170203_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_mime_type',
            field=models.CharField(default='image/jpeg', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='invoice',
            index_together=set([('customer', 'number')]),
        ),
        migrations.AlterIndexTogether(
            name='customercontact',
            index_together=set([('active', 'customer')]),
        ),
    ]
