# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20170206_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['sequence_order']},
        ),
    ]
